name: Build iOS IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
   steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 1. Cancelliamo eventuali residui e ricreiamo la cartella iOS pulita
      - run: |
          rm -rf ios
          flutter create . --platforms ios --org com.studiomusicale
          
      # 2. Scarichiamo le librerie (incluso Supabase)
      - run: flutter pub get

      # 3. Lanciamo la build forzando il "No Codesign"
      - run: flutter build ios --release --no-codesign
      
      # 4. Creiamo il pacchetto IPA (come abbiamo fatto prima)
      - name: Create IPA
        run: |
          mkdir -p Payload
          find build/ios/iphoneos -name "*.app" -exec cp -r {} Payload/ \;
          zip -r app.ipa Payload
          
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: my-app-ipa
          path: app.ipa
